
all :
	mvn install
	java -jar target/swingy-1.0-SNAPSHOT.jar

gui :
	mvn install
	java -jar target/swingy-1.0-SNAPSHOT.jar gui

console :
	mvn install
	java -jar target/swingy-1.0-SNAPSHOT.jar console

clean :
	mvn clean